env:
  node: true
parserOptions:
  ecmaVersion: 2021
  sourceType: "script"
rules:
  quotes:
    - error
    - single

  indent:
    - error
    - tab
  semi:
    - error
    - always
  no-unused-vars: error
ignorePatterns:
  - node_modules/
  - static/
  - docker/
  - logs/
  - uploads/
  - pic/